package com.mascot.medlink.model.enums;

public enum ClinicHospital {
    GENERAL_HOSPITAL,
    CITY_MEDICAL_CENTER,
    SUNSHINE_CLINIC,
    GREEN_VALLEY_HOSPITAL,
    LAKEVIEW_MEDICAL,
    MOUNTAIN_VIEW_CLINIC,
    PIONEER_HEALTHCARE,
    RIVERSIDE_HOSPITAL,
    STAR_HEALTH_CLINIC,
    OAKWOOD_MEDICAL_CENTER,
    CENTRAL_CARE_HOSPITAL,
    HARMONY_HEALTH_CLINIC,
    PEACEFUL_VALLEY_HOSPITAL,
    BRIGHT_FUTURE_CLINIC,
    GOLDEN_STATE_HOSPITAL
}
